# Generated by Django 3.0b1 on 2019-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaspNodeConfig', '0003_auto_20191105_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='stanza', max_length=40),
        ),
    ]
