# Generated by Django 3.0b1 on 2019-11-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaspNodeConfig', '0004_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
